[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps || npm install --legacy-peer-deps"]

[phases.build]
cmds = ["./node_modules/.bin/prisma generate", "npm run build"]

[start]
cmd = "./node_modules/.bin/prisma migrate deploy && node dist/server.js"
